Simd blog
Teradata/presto-tech pull request #1
Opened 2017-02-22 09:41 UTC by pnowojski

2017-02-22 11:39 UTC, ilfrin requested changes
I assume the formatting it good, haven't checked it, and that the general layout and look&feel is good

also ask Grzegorz to add his content here as well

2017-02-22 11:39 UTC, ilfrin commented on index.md
> +## Welcome to Teradata Presto GitHub Pages
change to "## Teradata Presto Technical Blogs" or something like that

2017-02-22 11:39 UTC, ilfrin commented on index.md
> +[JAVA and SIMD Blog post](blogs/simd.md)
how will we add more? is there a mechanism for it or we just add lines here? what about generating a menu etc? does that work somehow?

2017-02-22 11:47 UTC, ilfrin commented on index.md
> +## Welcome to Teradata Presto GitHub Pages
maybe we should add a subtitle or a paragraph like:
"This is a blog space for the Teradata Presto engineering team to share our thoughts and findings on the various software engineering topics we come across during the development of Presto - the open source distributed analytical SQL engine (https://github.com/prestodb/presto). Topics areas include, but are not limited to: Java performance tuning, database internals, SQL optimizers, etc"

2017-02-22 11:47 UTC, ilfrin commented on index.md
> +## Welcome to Teradata Presto GitHub Pages
or something like that ...

2017-02-23 08:01 UTC, pnowojski commented on index.md
> +## Welcome to Teradata Presto GitHub Pages
done

2017-02-23 08:02 UTC, pnowojski commented on index.md
> +[JAVA and SIMD Blog post](blogs/simd.md)
I couldn't find a way to generate a menu, maybe Grzesiek will improve it. For now, we can add it manually.

2017-03-16 14:03 UTC, merged